### ISSUE TITLE
Mapping functionality

### ISSUE THREAD

**Issue by vialcollet** [jdewit/AvroCsvBundle#17]
Hi and thanks for this brilliant work.
I was wondering how we can manage mappings with your bundle.

Thanks in advance.

**Comment by jdewit** [comment]
References are not supported yet. Look at Importer.php in the addRow method. I half started but ended up not needing this bundle anymore.

**Comment by vialcollet** [comment]
Hi @jdewit. Thank you for your answer.
I see that the ManyToOne looks completed. So if I have categories related OneToMany to subcategories, I can import subcategories no ?
