### ISSUE TITLE
InvalidConfigurationException: Unrecognized options "db_driver, batch_size, tmp_upload_dir, sample_count, objects" under "avro_csv"

### ISSUE THREAD

**Issue by alibelhaj** [jdewit/AvroCsvBundle#23]
Bonjour,
J'ai instaler votre bundle et je eu cette erreur 
InvalidConfigurationException: Unrecognized options "db_driver, batch_size, tmp_upload_dir, sample_count, objects" under "avro_csv"
version de symfony est 2.3

**Comment by insaneDev** [comment]
I have the same issue

**Comment by insaneDev** [comment]
Got it, change

`"avro/csv-bundle": "*"`
for
`"avro/csv-bundle": "dev-master"`

**Comment by Alex100dre** [comment]
Same here, unusable bundle...

**Comment by Alex100dre** [comment]
Oh thanks insaneDev, it works. 

But now, I have the error :
`No route found for "GET /export/users"`

With the config :
`avro_csv:
    db_driver: orm # supports orm
    batch_size: 15 # The batch size between flushing & clearing the doctrine object manager
    tmp_upload_dir: "%kernel.root_dir%/../web/uploads/tmp/" # The directory to upload the csv files to
    sample_count: 5 # The number of sample rows to show during mapping

    objects: # the entities/documents you want to be able to import/export data with
            users:
                class: AG2R\Bundle\InstantGagnantBundle\Entity\User # The entity/document class
                redirect_route: AG2RInstantGagnantBundle_connect # The route to redirect to after import
            participations:
                class: AG2R\Bundle\InstantGagnantBundle\Entity\Participation
                redirect_route: AG2RInstantGagnantBundle_connect`

**Comment by insaneDev** [comment]
Add routes to your app/config/routing.yml file


AvroCsvBundle:
    resource: "@AvroCsvBundle/Resources/config/routing.yml"
