### ISSUE TITLE
Unable to find template

### ISSUE THREAD

**Issue by oscarnevarezleal** [jdewit/AvroCsvBundle#24]
After following bundle installation steps, when going to upload lilnk there is a twig error.

Unable to find template "::layout.html.twig" in AvroCsvBundle::layout.html.twig at line 1.

**Comment by benisteel** [comment]
Hi.
I have the same error. Have you find the solution?

Thanks

**Comment by oscarnevarezleal** [comment]
No, sorry couldn´t find the solution

**Comment by MisatoTremor** [comment]
You should override the `layout.html.twig` template in your application.
