### ISSUE TITLE
not compatible with symfony 4

### ISSUE THREAD

**Issue by oliverfehmel** [jdewit/AvroCsvBundle#33]
**Bundle version(s) affected**:
avro/csv-bundle: dev-master

**Description**  
Require bundle with fresh copy of symfony 4.3 runs into error while clear:cache
Errortext: 

Cannot autowire service "Avro\CsvBundle\Controller\ImportController": argument "$caseConverter" of method "__construct()" references class "Avro\CaseBundle\Util\CaseConverter" but no such service exists. You should maybe alias this class to the existing "avro_case.converter" service.

**How to reproduce**  
Install fresh symfony 4.3 project (or use existing one). Require avro/csv-bundle

**Comment by MisatoTremor** [comment]
Fixed in 0.4.1
